### PR TITLE
Refresh expired subscriptions list after unsubscribe #160

### PR DESCRIPTION
**Pull request by knivets**

### CODE REVIEW

**Comment by smirolo** [comment]
I understand the change of name but why the variable declaration moved out of the if condition? Why also has the variables suffixed `ListVM` and not `App`?

Since `subscriptionsListVM` and `expiredSubscriptionsListVM` seem to be globals, it seem best to move them to the top of the file and comment how many global variables there are declared in the the file and what is their purpose.

It seems like all the `var app = ...` statement should also be reworked so as to have unique names for all globals declared. Otherwise we will have a similar bug popup when other components are moved around the templates.

The names of the globals should match the element ids in the HTML so as to make documentation easier.

**Comment by knivets** [comment]
The globals are needed in this particular case in order for two VMs to be able to communicate.

**Comment by knivets** [comment]
VM is a Vue naming convention https://vuejs.org/v2/guide/instance.html

**Comment by smirolo** [comment]
Resolution: Remove the `var app =`, `var expiredSubscriptionsListVM =`  and add a comment that explains why `subscriptionsListVM` is defined (aka where it is used).

**Pull request merged**
